### ISSUE TITLE
Town claims in a world is showing up in other worlds' maps 

### ISSUE THREAD

**Issue by Braynblocks** [TownyAdvanced/MapTowny#16]
## Describe the Bug
Town claims in the main world in my server is also showing up in the resource world, nether, and end world maps.

### Plugin Version
MapTowny-2.0.0-BETA-1 but also tried Pl3xMap-Towny v1.0.0

### Towny Version
Towny 0.97.2.0

### Pl3xMap Version
pl3xmap-1.18-2

### Server Software Version
Purpur 1.18.1 Build 1521 (still an issue on other versions)

**Comment by silverwolfg11** [comment]
I believe we talked over Discord and concluded that this wasn't a MapTowny issue, but rather a Pl3xMap issue. If this is not the case, please let me know, otherwise I will close this issue.
