### ISSUE TITLE
Can't Import MapTowny into my code

### ISSUE THREAD

**Issue by Goosius1** [TownyAdvanced/MapTowny#19]
## Describe the Bug
- I want to important MapTowny into another project, in order to use the API
- However the steps in the wiki do not work i.e. these POM lines do not find the library 
```<repositories>
    <repository>
         <id>jitpack.io</id>
         <url>https://jitpack.io</url>
    </repository>
</repositories>
...
<dependency>
    <groupId>com.github.TownyAdvanced</groupId>
    <artifactId>MapTowny</artifactId>
    <version>v2.0.0-BETA-1</version>
</dependency>
```

## Expected Behavior
- I should be able to import the library using Maven
 
### Plugin Version
N/A

### Towny Version
N/A

### Pl3xMap Version
N/A

### Server Software Version
N/A

**Comment by silverwolfg11** [comment]
Sorry for the delay in response. 

This is an issue with Jitpack not being able to handle the Maven toolchain plugin by default. With the release of 2.0.0 BETA-2, the plugin will be hosted on Glare's maven repository (and the wiki page will be updated with the correct information) which should work.

**Comment by silverwolfg11** [comment]
Fixed! The [API wiki page](https://github.com/TownyAdvanced/MapTowny/wiki/MapTowny-API) is updated with the correct information now!
