### ISSUE TITLE
Tax percent sign should comes after the number

### ISSUE THREAD

**Issue by PolitcubesDeveloperUnchained** [TownyAdvanced/MapTowny#24]
**Please remove the percent sign, it's confusing and doesn't display correctly. Percentages must be written after the number. The percent sign always comes after the number, never before**

https://github.com/TownyAdvanced/MapTowny/blob/c285b16aeff4a0b9ea59dcbfee2ccda7785f6eb7/maptowny-plugin/src/main/java/me/silverwolfg11/maptowny/managers/TownInfoManager.java#L147-L154

**Comment by silverwolfg11** [comment]
Oh whoops, I didn't even notice I wrote it that. But I agree, it's probably easier to remove it from the format and let people add it manually.

**Comment by silverwolfg11** [comment]
Fixed in [release 2.0.0](https://github.com/TownyAdvanced/MapTowny/releases/tag/v2.0.0).
