### ISSUE TITLE
if i make a cube it will fill everything in the middle. dynmap

### ISSUE THREAD

**Issue by Roetchi** [TownyAdvanced/MapTowny#29]
When someone makes claims like this and when they finally connect the 2 ends inside of the claimed ring shows claimed on the map but it's not claimed in-game

![image](https://user-images.githubusercontent.com/109714825/180131405-ee8f277b-3481-43ea-83f7-55d9bd54de3f.png)
https://imgur.com/kcjKrKN

I found someone having the same problem too
![image](https://user-images.githubusercontent.com/109714825/180131485-0119a142-d5aa-4508-b807-0bbaa4b6168d.png)

**Comment by LlmDl** [comment]
This is a limitation of Dynmap. If you used plexmap, squaremap or bluemap this is not an issue.
