### ISSUE TITLE
Add Pl3xMap v2 support

### ISSUE THREAD

**Issue by Folas1337** [TownyAdvanced/MapTowny#36]
Pl3xMap somewhat recently (August this year) released Pl3xMap v2 which apparently is "a complete rewrite of [the] original Pl3xMap plugin from the ground up." (taken from their Discord announcement).

It would be cool to see it supported some time soon. Here is the repository: https://github.com/BillyGalbreath/Pl3xMap/tree/v2

**Comment by Folas1337** [comment]
I've gotten this response from Billy, the pl3xmap developer that I'll just forward:

```
The documentation is lacking, but I have some examples in the GitHub repo you can look at to see how stuff works

https://github.com/BillyGalbreath/Pl3xMap/wiki/Pl3xMap-API
```

**Comment by MWHunter** [comment]
Duplicate https://github.com/TownyAdvanced/MapTowny/issues/34

**Comment by silverwolfg11** [comment]
I was working on Pl3xMap v2 support, however I ran into a big issue with setting properties on map markers (e.g. the color,name,etc of the claim that shows up on the map). I reported the [issue](https://github.com/BillyGalbreath/Pl3xMap/issues/126) on the Pl3xMap github, but haven't received a response or fix yet. 

Once a fix is pushed to Pl3xMap, I'll release MapTowny's support for Pl3xMap v2. Thank you for your suggestion!

**Comment by Folas1337** [comment]
Ah I see, thanks for clarifying. I'll patiently wait for the update then, no worries.

I just wanted to make sure it's not being forgotten :)

**Comment by Folas1337** [comment]
Yay, it's been fixed in Pl3xMap so I guess you can continue working on this :D

**Comment by silverwolfg11** [comment]
Added in [version 2.1.0](https://github.com/TownyAdvanced/MapTowny/releases/tag/v2.1.0).
