### ISSUE TITLE
New placeholders %public% %peaceful%

### ISSUE THREAD

**Issue by Luciusred** [TownyAdvanced/MapTowny#37]
Hi i think it will be cool add new placeholders like in dynmap-towny
Add new placeholders 
%public% - town is public or not (everyone can join or not)
%peaceful% - have neutrality or not

**Comment by silverwolfg11** [comment]
Hi I'll take a look at adding this in the next minor release of MapTowny. Thank you for the suggestion!

**Comment by silverwolfg11** [comment]
Added in [version 2.1.0](https://github.com/TownyAdvanced/MapTowny/releases/tag/v2.1.0).
