### ISSUE TITLE
Add/ensure support for pl3xmap v3

### ISSUE THREAD

**Issue by 1ByteBit** [TownyAdvanced/MapTowny#44]
**Is your feature request related to a problem? Please describe.**
Pl3xmap released v3 which is extremely better then v2 in terms of speed and quality

**Describe the solution you'd like**
*Official* pl3xmap v3 support, in the same way of v1 and v2

**Describe alternatives you've considered**
N/A (I think)

**Additional context**
N/A

**Comment by ShackInTheMiddle** [comment]
+1 it's a must, add it faster kkthx

**Comment by Agaloth** [comment]
I added pl3xmap v3 support, you can try to compile it yourself, either check my pull request or my maptowny fork, don't reload pl3xmap or maptowny until it's merged into maptowny officially and add a outpost icon as well in the config while having it it can cause into town icons not loading.

**Comment by Agaloth** [comment]
Additionally I removed pl3xmap v1 support on my fork/pull request as it's an ancient version and probably no one even uses it anymore since it doesn't get support

**Comment by Agaloth** [comment]
https://github.com/TownyAdvanced/MapTowny/pull/45
