### ISSUE TITLE
Pl3xMap and MapTowny produce diagonal lines in plot renders

### ISSUE THREAD

**Issue by Folas1337** [TownyAdvanced/MapTowny#56]
## Describe the Bug
I just recently updated to the Alpha and noticed how in certain situations the lines don't line up as they should with Pl3xMap, producing diagonal lines instead of vertical ones.

## Expected Behavior
![image](https://github.com/TownyAdvanced/MapTowny/assets/39222968/1050a4e0-d86e-4512-869e-c308f8e57aaa)
The lines should go as shown in red but they actually connect diagonally which is obviously not correct.

### Plugin Version
MapTowny version 3.0.0-ALPHA-1

### Towny Version
Towny version 0.100.1.0

### Pl3xMap Version
Pl3xMap v3 1.20.4-SNAPSHOT (paper) git-3f104c4
*I know this is a snapshot version but it should have nothing to do with this rendering bug.*

### Server Software Version
Paper version git-Paper-447 (MC: 1.20.4)

## Additional Comments
None

**Comment by silverwolfg11** [comment]
Thanks for reporting this! Could you please post the results of `towny map big` ran in-game in the area shown by the map?

**Comment by silverwolfg11** [comment]
Should be fixed in v3.0.0-alpha-2, please try the [second alpha version](https://github.com/TownyAdvanced/MapTowny/releases/tag/v3.0.0-alpha-2) and let me know if it doesn't work. Thanks for reporting this!

**Comment by Folas1337** [comment]
I can confirm it's no longer happening, I just updated and checked.

Thanks for the update and take care 👋
